name: ummaly
description: "Halal verification app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core UI and icons
  cupertino_icons: ^1.0.8

  # Firebase core services and authentication
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  # Prebuilt Firebase Auth UI
  flutterfire_ui: ^0.4.0
  provider: ^6.1.2

  # Localization support
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^5.0.0

flutter:

  # Enables use of Material Design icons
  uses-material-design: true

  # Localisation assets for easy_localization
  assets:
    - assets/translations/

  # Font and image assets can be configured here as needed
  # Example:
  # assets:
  #   - images/logo.png

  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
