name: ummaly
description: "Halal verification app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core UI and icons
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.6

  # Firebase core services and authentication
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Facebook auth
  flutter_facebook_auth: ^7.1.2

  # State management
  provider: ^6.1.2

  # Localization support
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
