name: ummaly
description: "Halal verification app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.2.0
  dio: ^5.4.3+1   # ✅ NEW - For API requests to backend
  flutter:
    sdk: flutter

  # Core UI and icons
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1

  # Firebase core services and authentication
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # Facebook auth
  flutter_facebook_auth: ^7.1.2

  # State management
  provider: ^6.1.2
  get: ^4.6.6   # ✅ Already added earlier - For reactive state management and navigation

  # Localization support
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/translations_lazy/
    - assets/images/ummaly_logo.jpg
