// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2_WaglG2mJdmzl1Mxrw4nMPDrNcvvWc',
    appId: '1:116981186736:web:4a25a39a75d4f61861fb75',
    messagingSenderId: '116981186736',
    projectId: 'ummaly-c201b',
    authDomain: 'ummaly-c201b.firebaseapp.com',
    storageBucket: 'ummaly-c201b.firebasestorage.app',
    measurementId: 'G-06EQ283Q3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnbgDATsyI7jKnZFEg3_j3JeElG6JQyg',
    appId: '1:116981186736:android:6bacd15b204ca74961fb75',
    messagingSenderId: '116981186736',
    projectId: 'ummaly-c201b',
    storageBucket: 'ummaly-c201b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoEMZ5q-XdFdT91ARfSnAyi-wpOAnZA0U',
    appId: '1:116981186736:ios:67cc78f33c5c4a0c61fb75',
    messagingSenderId: '116981186736',
    projectId: 'ummaly-c201b',
    storageBucket: 'ummaly-c201b.firebasestorage.app',
    iosBundleId: 'com.ummaly.ummaly',
  );
}
